### ISSUE TITLE
Wake word detection stops working 

### ISSUE THREAD

**Issue by dumpfheimer** [rhasspy/wyoming-openwakeword#2]
Hi!

First of all, thanks for your work! I am absolutely psyched to have an offline voice assistant with wake word detection, absolutely fabulous 🚀

I am using Home Assistant's assistant with Wyoming piper + whisper + openwakeword. All 3 Wyoming apps are run via docker. Plus 3 Atom Echo running 2023.10.0b1

I have the following issue:

My wake word detection stops working after a few minutes. (Also, it seems like only one device at a time can check for a wake word)

I turned on debug logging for openwakeword and it stops after these lines:

```
DEBUG:wyoming_openwakeword.handler:Client connected: 343809002501645
DEBUG:wyoming_openwakeword.handler:Receiving audio from client: 343809002501645
```

I am guessing that a stalled connection is blocking the server from handling more requests, or something like this.

Before this I had multiple client connections per minute, now it's quiet.

Restarting the docker contsiner (and then reenabling wake word detection) fixes the issue.

It looks like the Wyoming server was meant to be asynchronous, so I'm not sure if this issue maybe should rather be in Wyoming project?

Thanks a lot!

**Comment by diplix** [comment]
i can confirm this behaviour when streaming audio via [homeassistant satellite](https://github.com/synesthesiam/homeassistant-satellite). while it’s working it’s absolutly amazing, however wakeword detection always stops after a while and i too have to restart the wyoming-openwakeword docker container to resume wake word detection. there’s no error logged in the container and  i also guess the problem is related to the wyoming integration in home assistant or some kind of connection problem.

**Comment by dumpfheimer** [comment]
So, I dug a bit deeper into the code. 

If I understand correctly, it is indeed the openwakeword part, that is preventing concurrent execution. (there are multiple locks in the code)
This potentially leads to multiple problems:

- If multiple satellites are used, only one at a time can use wake word detection.
- If a connection is staled, the server is locked up (not proven, hypothetically; but it seems like this is happening)

**Comment by dumpfheimer** [comment]
Okay, now my best bet is that it is a locking issue.
There are, at some points, multiple locks acquired, and it seems like in different order, which could cause a deadlock

**Comment by synesthesiam** [comment]
Please update to version 1.8.0 of the add-on (or container)

**Comment by thomclae33** [comment]
Updated the container to the latest version, but I have the same issue: after turning on the wakeword, it works once and after that stops working (unless I turn it back off and on again).

**Comment by dumpfheimer** [comment]
I have had similar issues. If you can fix it by turning off and on voice detection of the esp it is not the issue fixed in openwakeword. 

Which Firmware are you using?
Have you tried the 2023.10.1 firmware for the echo?

**Comment by thomclae33** [comment]
Thank you, that did the trick indeed!

**Comment by pdarcos** [comment]
Hi, I see this issue is now closed but I have the same problem and am not sure how to fix it. I am running  ESPHome 2023.11.0 on my Echo but it seems to never detect the wake word (using the default OK Nabu)

> Logs m5stack-atom-echo-869a5c.yaml
> INFO ESPHome 2023.11.0
> INFO Reading configuration /config/esphome/m5stack-atom-echo-869a5c.yaml...
> INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
> INFO Starting log output from m5stack-atom-echo-869a5c.local using esphome API
> INFO Successfully connected to m5stack-atom-echo-869a5c in 0.162s
> INFO Successful handshake with m5stack-atom-echo-869a5c in 0.094s
> [19:50:09][I][app:102]: ESPHome version 2023.11.0 compiled on Nov 15 2023, 17:45:13
> [19:50:09][I][app:104]: Project m5stack.atom-echo-voice-assistant version 1.0

Core    2023.11.2
Supervisor   2023.11.3
Operating System  11.1
Frontend 2 0231030.2

![Screenshot from 2023-11-15 19-44-24](https://github.com/rhasspy/wyoming-openwakeword/assets/32959420/34a4f49b-fbd0-47e9-967d-dbe12f284615)

Do I need to update or tweak anything to get it to work?

Thanks
